"""Rebuild the numerical prose from verified full-S669 result files."""
from pathlib import Path
import json,re
p=Path('paper/manuscript.tex');s=p.read_text();r=lambda n:json.loads((Path('results')/n).read_text()); b=r('s669_group_holdout.json');g=r('group_sensitivity.json');loo=r('leave_one_pdb_out.json');z=r('error_strata.json');sp=r('sparse_group_sensitivity.json')['thresholds']; count=r('accession_count.json');seq=r('sequence_overlap_audit.json')
def para(start,end,new):
 global s
 a=s.index(start);c=s.index(end,a);s=s[:a]+new+'\n'+s[c:]
# Preserve the technical and disease-target discussion; replace every stale numerical paragraph and figure interpretation.
s=s.removeprefix('% SUPERSEDED: The numerical S669 results below belong to the old 420-row mapping and must not be distributed as the corrected 669-row study.\n')
para('We tested a small residue-graph','\\end{abstract}',f'''We tested a small residue-graph neural network for single-amino-acid stability-change prediction on the experimental S669 benchmark. A corrected mapping derives the mutated sequence site from the only wild-type/mutant sequence difference and independently verifies the PDB residue number. All 669 rows yield structure graphs, covering 94 PDB accessions. A PDB-group holdout contains 66 variants across 24 unseen structures. The graph model has Spearman correlation {b['metrics']['gnn']['spearman']:.3f} and mean absolute error (MAE) {b['metrics']['gnn']['mae']:.3f} kcal/mol; stored GeoDDG-Seq predictions have {b['metrics']['GeoDDG-Seq_dir']['spearman']:.3f} and {b['metrics']['GeoDDG-Seq_dir']['mae']:.3f} on the same rows. The graph model did not outperform the existing predictor on MAE. A separate partial-export FireProtDB accession audit finds 1,470 direct residue-number-matched rows from 74 PDBs, but it is not a complete database census. Disease-target structures and published suppressor assays define limitations, not evidence that our model discovered therapeutic rescues. No predicted second-site mutation has been validated experimentally.''')
para('S669 was obtained from','\\section{Mutation and residue graph construction}',f'''S669 was obtained from the public GeoStab repository and its Zenodo release. The 94 PDB identifiers in S669 were fetched from RCSB and all 94 yielded at least one accepted graph. In an earlier draft, we incorrectly treated the numerical residue label in the mutation name as the sequence offset; this rejected 249 genuine variants. The corrected pipeline finds the sole sequence difference, aligns it to the structure and independently checks the label against the observed PDB residue number. It accepts {b['audit']['valid']} of {b['audit']['total']} rows. The superseded 420-row analysis is isolated in clearly labeled legacy folders and is not cited as the current result. An incomplete FireProtDB CSV response (network timeout after approximately 300 MB) was filtered in chunks. This remains a partial snapshot. Of 1,112,013 observed export rows examined, 3,865 met numeric-DDG, PDB and substitution filters across 132 fetched structures. Direct wild-type amino-acid and numbered-residue checks matched 1,470 rows on 74 structures; these checks alone do not establish equivalent assay state or construct. The 94 S669 PDBs and 74 directly mapped FireProtDB PDBs overlap in 11 accessions, yielding 157 unique mutation-data structures; six separately studied disease-mutant structures raise the accession-backed used total to {count['union']}. The number of source studies remains two. Fetching a PDB without processing it is not counted.''')
s=s.replace('A missing or mismatched C-alpha residue rejects the row.','A missing or mismatched C-alpha residue rejects the row. The mutation label is checked against the aligned PDB residue number rather than assumed to be the sequence offset; insertion codes and construct numbering require explicit scrutiny.')
para('An independent exact-sequence audit','The hard non-overlap requirement',f'''An independent exact-sequence audit finds {seq['total_unique_sequences']} unique reference strings across 94 accepted PDBs, with {seq['train_sequences']} in training and {seq['test_sequences']} in testing and {seq['exact_sequence_overlap']} exact train/test overlaps. Exact-string separation does not rule out homologs, fold-level leakage, or overlap with historical third-party predictor training sets. The hard non-overlap requirement is''')
para('From 669 S669 rows,','Reported metrics are',f'''All 669 S669 rows yielded graphs: {b['split']['train']} training variants from {len(b['split']['train_pdbs'])} PDBs and {b['split']['test']} test variants from {len(b['split']['test_pdbs'])} unseen PDBs. The two largest test structures account for {100*g['largest_two_row_fraction']:.1f}\\% of test rows. The previous 420-row draft reflected a construct-numbering error and its quantitative outputs are not comparable with this corrected split. Reported metrics are''')
a=s.index('\\begin{center}\\begin{tabular}{lrrr}');e=s.index('\\end{center}',a)+len('\\end{center}')
keys=[('Train mean','train_mean'),('Ridge','ridge'),('Residue GNN','gnn'),('GeoDDG-Seq, stored','GeoDDG-Seq_dir'),('GeoDDG-3D, stored','GeoDDG-3D_dir'),('PremPS, stored','PremPS_dir'),('DDGun, stored','DDGun_dir'),('DDMut, stored','DDMut_dir')]
t='\\begin{center}\\begin{tabular}{lrrr}\\hline Method & Test variants & MAE & Spearman\\\\\\hline '
for name,key in keys:
 m=b['metrics'][key];t+=f"{name} &{m['n']}&{m['mae']:.4f}&{('undefined' if m['spearman'] is None else format(m['spearman'], '.4f'))}\\\\"
t+='\\hline\\end{tabular}\\end{center}'
s=s[:a]+t+s[e:];s=s.replace('The PremPS value uses 148 available predictions; other rows use 149.','Every displayed method has 66 stored predictions in this holdout.')
para('The fixed test set contains','\\section{Group-weighting sensitivity}',f'''The fixed test set contains 46 negative and 20 nonnegative experimental DDG labels, describing the S669 column, not a clinical classification. Against stored GeoDDG-Seq predictions, GNN absolute error was lower on {z['gnn_better_rows']} of 66 variants and higher on {z['comparator_better_rows']}. At PDB level, it had lower average error on {z['gnn_better_pdb_groups']} of 24 structures and higher error on {z['comparator_better_pdb_groups']}. Four observed-label bins contain {', '.join(str(v['n']) for v in z['bins'])} variants; GNN-minus-comparator MAE differences are {', '.join(format(v['delta_mae'], '+.3f') for v in z['bins'])} kcal/mol. The positive-label tail has only {z['bins'][-1]['n']} rows. These post hoc bins cannot serve as a prospective mutation-ranking gate. The aggregate GNN MAE remains worse, and no subgroup is claimed as a rescue discovery.\\begin{{figure}}[!htbp]\\centering\\includegraphics[width=.86\\linewidth]{{figure_error_strata.pdf}}\\caption{{Observed-label error strata; labels are known only after measurement and group samples are small.}}\\end{{figure}}''')
para('The committed subset audit finds','An exploratory group-bootstrap',f'''The corrected audit finds $\\overline\\delta_{{\\mathrm{{row}}}}={g['row_weighted_delta_mae']:+.4f}$ and $\\overline\\delta_{{\\mathrm{{protein}}}}={g['protein_equal_delta_mae']:+.4f}$ kcal/mol across $K={g['protein_groups']}$ groups. The signs differ under unequal weighting, which makes a single superiority claim unsafe. An exploratory group-bootstrap''')
para('The 2.5\\% and 97.5\\% bootstrap quantiles','\\section{Leave-one-structure-out sensitivity}',f'''The 2.5\\% and 97.5\\% protein-equal bootstrap quantiles are $[{g['bootstrap_protein_equal_95'][0]:+.4f},{g['bootstrap_protein_equal_95'][2]:+.4f}]$ kcal/mol; they include zero. A naive row-bootstrap interval is $[{g['bootstrap_row_95'][0]:+.4f},{g['bootstrap_row_95'][2]:+.4f}]$, also crossing zero. These descriptive intervals condition on one fixed partition; resampling related variants within a protein is not a new validation cohort. The reversal between row and protein weighting is a warning about small and uneven groups, not evidence for new-protein superiority.''')
para('The first benchmark split contains','\\begin{equation}\\mathrm{MAE}_{\\mathrm{protein',f'''The fixed benchmark split contains 66 test variants across 24 PDB groups. For a separate ridge-baseline stress test, each of the {loo['pdb_groups']} graph-usable PDB structures is held out once; scaling and ridge fitting use only the remaining structures. The GNN is not retrained in these folds. Across {loo['variants']} out-of-fold rows, ridge MAE is {loo['ridge_row_mae']:.4f} kcal/mol row-weighted and {loo['ridge_protein_equal_mae']:.4f} protein-equal. Train-mean MAE is {loo['train_mean_row_mae']:.4f} and {loo['train_mean_protein_equal_mae']:.4f}, respectively. Ridge beats train mean in {loo['ridge_better_pdbs']} of {loo['pdb_groups']} held-out structures. Median group size is {loo['median_group_size']:.0f}, and {loo['singleton_pdbs']} groups contain one variant. These are ridge sensitivity results, not GNN cross-validation, and exact-sequence checks do not exclude all homologs.''')
s=s.replace('these 52 folds','these 94 folds')
para('The fixed test split is especially vulnerable','\\section{FireProtDB as a separate audit',f'''Seven of the 24 held-out PDBs have a single test variant. Removing those groups leaves {sp[1]['retained_proteins']} PDBs and {sp[1]['retained_variants']} variants; {sp[1]['gnn_better_proteins']} PDBs then have lower GNN error. Requiring at least five variants retains just {sp[4]['retained_proteins']} PDBs and {sp[4]['retained_variants']} rows, with no lower-error GNN group. The row-weighted GNN-minus-comparator MAE differences at thresholds 1, 2 and 5 are {sp[0]['row_weighted_delta_mae']:+.3f}, {sp[1]['row_weighted_delta_mae']:+.3f} and {sp[4]['row_weighted_delta_mae']:+.3f} kcal/mol, respectively. This changes which proteins are represented after seeing the fixed test set; it is descriptive sensitivity, not model selection or an independent benchmark.\\begin{{figure}}[!htbp]\\centering\\includegraphics[width=.86\\linewidth]{{figure_sparse_groups.pdf}}\\caption{{Row-weighted comparator gap after group-size thresholds; the sample changes each time.}}\\end{{figure}}''')
s=s.replace('Its logarithmic horizontal axis exposes that the high-error small groups affect protein-equal summaries more than row-weighted summaries.','Its logarithmic horizontal axis shows uneven group sizes; no one figure establishes a general population error estimate.').replace('420 mutation rows for 420 independent protein generalization trials','669 mutation rows for 669 independent protein generalization trials')
s=s.replace('The source manifest records the URL and checksum of S669-linked PDBs, and the accession ledger records 126 distinct used PDB structures: 120 from mutation-mapped S669 and partial FireProtDB records plus six disease-mutant structures directly compared with wild type.','The source manifest records URL and checksum for S669-linked PDBs. The corrected accession ledger records 163 used PDB structures: 157 unique S669 or partial FireProtDB mutation-data PDBs plus six disease-mutant structures directly compared with wild type.')
s=s.replace('twenty-five scientific data or literature surfaces, or twenty-seven including GitHub and Drive workflow checks','twenty-five scientific data or literature surfaces, excluding GitHub and Drive infrastructure')
p.write_text(s)
